### ISSUE TITLE
CarControl doesn't work

### ISSUE THREAD

**Issue by Doerd** [AutonomousCarProject/CarControl#3] opened 2018-07-16 21:06 UTC

**Comment by sameer-s** [comment] 2018-07-17 16:07
Unable to reproduce issue.

**Comment by Doerd** [comment] 2018-07-18 21:43
I reproduced it by hitting "run" in Eclipse.

**Comment by sameer-s** [comment] 2018-07-18 23:46
Interesting. Have you tried turning it off and back on again?

**Comment by Doerd** [comment] 2018-07-23 17:35
No I didn't think about that

**Comment by sameer-s** [comment] 2018-08-06 19:27
Resolved in #90 .

**Comment by rewinded** [comment] 2018-08-06 19:35
good

**Closed by rewinded** 2018-08-06 19:35 UTC
